{{- if not .Values.neo4j.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-neo4j
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.neo4j.auth.password | quote }}
{{- end }}