apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fc-portal.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fc-portal.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fc-portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fc-portal.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fc-portal.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "fc-portal.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVER_PORT
              value: "{{ .Values.service.port }}"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
              value: {{ .Values.keycloak.jwtIssuer }}
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FC_CLIENT_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "fc-portal.fullname" . }}-keycloak-client
                  key: client-secret
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: {{ .Values.probes.path }}
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: {{ .Values.probes.path }} 
          #     port: http
          #   initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.probes.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- range .Values.ingress.tls }}
            - name: {{ .secretName | replace "." "-" }}
              mountPath: /opt/fc-portal/certs
              readOnly: true
            {{- end }}
      volumes:
        {{- range .Values.ingress.tls }}
        - name: {{ .secretName | replace "." "-" }}
          secret:
            secretName: {{ .secretName }}
            items:
              - key: ca.crt
                path: {{ .secretName }}.crt
            defaultMode: 420
        {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.restartPolicy }}
      restartPolicy: {{ .Values.restartPolicy }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}