apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-config
data:
  # property-like keys; each key maps to a simple value
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: http://key-server/realms/gaia-x
      FEDERATED_CATALOGUE_BASE_URI: http://fc-server



      