apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fc-service.fullname" . }}-portal
  labels:
    {{- include "fc-service.labels" . | nindent 4 }}
    app: portal
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app : portal
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: portal
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePortal.secret }}
      serviceAccountName: {{ include "fc-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: fc-portal
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.imagePortal.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: portal-config          # The ConfigMap this value comes from.
                  key: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
            - name: FEDERATED_CATALOGUE_BASE_URI
              valueFrom:
                configMapKeyRef:
                  name: portal-config          # The ConfigMap this value comes from.
                  key: FEDERATED_CATALOGUE_BASE_URI
            
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FC_CLIENT_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: fc-keycloak-client-secret          # The ConfigMap this value comes from.
                  key: keycloak_client_secret
          ports:
            - name: http
              containerPort: {{ .Values.servicePortal.port }}
              protocol: TCP  
                    
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: http


