{{- if not .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fc-service.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fc-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgresql.auth.password | quote }}
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | quote }}
{{- end }}